version: "3.9"
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.backend
    container_name: avatar-backend-container
    ports:
      - "5001:5000"
    networks:
      - app_network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.frontend
    container_name: avatar-frontend-container
    ports:
      - "5173:5173"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
