FROM python:3.9-slim

# Directorio de trabajo
WORKDIR /app

# Copia los archivos de requerimientos y los instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Código de la app al contenedor
COPY . .

# Expone el puerto Flask
EXPOSE 5000

# Variables de entorno para Flask
ENV FLASK_APP=app.py
ENV FLASK_ENV=development
ENV FLASK_RUN_HOST=0.0.0.0  
ENV FLASK_RUN_PORT=5000    

# Comando de arranque (para desarrollo y producción)
CMD ["flask", "run"]
