name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar acceso SSH y ejecutar comandos en EC2
    - name: Deploy to EC2
      env:
        AWS_PEM_KEY: ${{ secrets.AWS_PEM_KEY }}
        USER_URL: ${{ secrets.USER_URL }}
      run: |

        echo "$AWS_PEM_KEY" > Key-Avatares.pem
        chmod 600 Key-Avatares.pem
        
        << 'EOF'
        echo "Clonando o actualizando el repositorio..."
        if [ ! -d ~/ProyectoDevops ]; then
            git clone https://github.com/chelemovil87/Proyecto-Devops.git ~/ProyectoDevops || {
            echo "Error: No se pudo clonar el repositorio."
            exit 1
            }
        else
            cd ~/ProyectoDevops && git pull origin main || {
            echo "Error: No se pudo actualizar el repositorio."
            exit 1
          }
        fi

          echo "Ejecutando script de despliegue..."
          cd ~/ProyectoDevops &&
          chmod +x deploy_k8s.sh &&
          ./deploy_k8s.sh || {
          echo "Error: El script de despliegue falló."
          exit 1
          }
        EOF
